# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=150)),
                ('alias', models.CharField(max_length=150)),
            ],
        ),
    ]
