# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20161011_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('run_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=150)),
                ('game', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1500)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('youtube_link', models.CharField(max_length=150)),
                ('runners', models.ManyToManyField(to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='tags',
            field=models.ManyToManyField(to='runs.Tag'),
        ),
    ]
